### PR TITLE
Export components

### PR DESCRIPTION
**Pull request by TheNoim**
You don't always want to install froala as global vue plugin. If you only need froala in one component, you need to be able to register the components local. 

Signed-off-by: Nils Bergmann <nilsbergmann@noim.io>

### CODE REVIEW

**Comment by mannyyang** [comment]
Would love to see this featured merged in, it would helpful in situations where you're using it in a component library.

**Comment by TheNoim** [comment]
Ok, I nearly completely changed the file because of formatting. Maybe this is the reason why they do not merge the pr. However, then they should provide feedback.

**Comment by mannyyang** [comment]
@nikpok Is there any reason why we wouldn't want to export the components individually? The main default export will still exist.

**Comment by mannyyang** [comment]
pinging @stefanneculai

**Comment by ThomasTr** [comment]
also for me: want to import editor only in certain places

pinging @stefanneculai

**Comment by navneetnagpal** [comment]
merged in separate PR.

**Comment by TheNoim** [comment]
Thanks

**Comment by ilrock** [comment]
How can this be used?

**Comment by TheNoim** [comment]
Excuse me, what exactly do you mean?

**Pull request closed without merging**
