### PR TITLE
Framework upgrade for vue-froala from Vue 2 to Vue 3 

### PR DESCRIPTION
**Pull request by AkshayAccolite**
Framework upgrade

### CODE REVIEW

**Comment by AkshayAccolite** [comment]
@harasunu-narayan can you please have a look into this PR?

**Comment by vivek-accolite-801** [comment]
Hi @harasunu-narayan 

As Vue3 code is not compatible with Vue2 - it needs to be maintained as a separate branch or separate repo.

**Comment by AkshayAccolite** [comment]
Here is the link to the document which include the list of breaking changes that are related to vue upgrade.

**Comment by harasunu-narayan** [comment]
@AkshayAccolite , @vivek-accolite-801 ,
Kindly update the dependencies to address the vulnerabilities fixed with latest versions. Refer the dependabot PRs.

**Comment by AkshayAccolite** [comment]
@harasunu-narayan 
Here is the link to the dependabot generated PRs in the "vivek-accolite-801/vue-3-support" repository. I believe this is what you hoped for. 
https://github.com/vivek-accolite-801/vue-froala-wysiwyg/pulls

**Comment by AkshayAccolite** [comment]
@harasunu-narayan 
1. Please mention which license do we need to use from the SPDX license list - https://spdx.org/licenses/    to resolve the warning  "License should be a valid SPDX license expression".

**Comment by AkshayAccolite** [comment]
@harasunu-narayan 
The warnings are fixed.
There are 13 vulnerabilities that can not be fixed due to the following dependencies do not have  non vulnerable version.

1. vue-html-loader  - https://snyk.io/advisor/npm-package/vue-html-loader
2. babel-core   - https://snyk.io/advisor/npm-package/babel-core
3. isparta-loader - https://snyk.io/advisor/npm-package/isparta-loader
4. isparta - https://snyk.io/advisor/npm-package/isparta
5.  inject-loader -  https://snyk.io/advisor/npm-package/inject-loader
6. babel-register - https://snyk.io/advisor/npm-package/babel-register

7. html-webpack-plugin : Upon upgrading this plugin to version v4+ we get Type error during build process.

**Comment by harasunu-narayan** [comment]
@AkshayAccolite ,
Could you verify the Readme and update the changes required, if any.

**Comment by AkshayAccolite** [comment]
Hi @harasunu-narayan

**Comment by AkshayAccolite** [comment]
Hi @harasunu-narayan 
I have updated the Readme file with necessary changes.

**Review by harasunu-narayan — APPROVED** [review]

**Pull request merged**
